# Generated by Django 6.0.1 on 2026-02-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='State',
            new_name='City',
        ),
    ]
