# Generated by Django 6.0.1 on 2026-02-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_state_employee_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Contact',
            new_name='contact',
        ),
    ]
