# Generated by Django 6.0.1 on 2026-02-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.BigIntegerField()),
                ('Image', models.ImageField(upload_to='image')),
                ('Code', models.CharField(max_length=20)),
                ('Dept', models.CharField(max_length=20)),
            ],
        ),
    ]
