# Generated by Django 6.0.1 on 2026-02-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Dept', models.CharField(max_length=40)),
                ('Query', models.TextField()),
                ('Status', models.CharField(default='Pending')),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Dept', models.CharField(max_length=40)),
                ('Query', models.TextField()),
                ('reply', models.CharField(null=True)),
            ],
        ),
    ]
