# Generated by Django 6.0.1 on 2026-02-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_query_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='Dept',
            new_name='Department',
        ),
    ]
