# Generated by Django 6.0.1 on 2026-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_dept_query_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reply',
        ),
        migrations.AddField(
            model_name='query',
            name='reply',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
