# Generated by Django 6.0.1 on 2026-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_reply_query_reply_alter_query_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='Department',
            new_name='Departments',
        ),
    ]
